# Build
FROM container-registry.oracle.com/graalvm/native-image:21 AS builder

WORKDIR /build

# Copy Gradle wrapper and configuration files
COPY gradlew .
COPY gradle gradle
COPY build.gradle settings.gradle ./

# Ensure the wrapper is executable and download dependencies
RUN chmod +x gradlew && ./gradlew --version

# Copy source code
COPY src ./src

# Build the native image
# The task name is 'nativeCompile' if you are using the GraalVM Native Build Tools plugin
RUN ./gradlew nativeCompile -x test

# Runtime
FROM alpine:latest
RUN apk add --no-cache gcompat

WORKDIR /app

# Copy the compiled binary from the builder stage
COPY --from=builder /build/build/native/nativeCompile/runestone-bank .

COPY .env .env

ENTRYPOINT ["./runestone-bank"]