services:
  db:
    image: postgres:15-alpine
    container_name: runestone-db
    restart: always
    command: ["postgres", "-c", "wal_level=logical", "-c", "max_wal_senders=10", "-c", "max_replication_slots=10"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: runestone_bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d runestone_bank" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - runestone-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: runestone-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - runestone-network
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: runestone-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - runestone-network

  app:
    image: ${DOCKER_IMAGE:-runestone-app-local}
    build:
      context: ../server
      dockerfile: ../infra/Dockerfile.dev
#    env_file:
 #     - ../server/.env
    container_name: runestone-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/runestone_bank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      APP_PASSWORD: ${APP_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - runestone-network

  connect:
    image: debezium/connect:2.5
    container_name: runestone-connect
    restart: always
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      # KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      # VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    depends_on:
      kafka:
        condition: service_started
      db:
        condition: service_healthy
    networks:
      - runestone-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: runestone-kafka-ui
    restart: always
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      kafka:
        condition: service_started
    networks:
      - runestone-network

volumes:
  postgres_data:

networks:
  runestone-network:
    driver: bridge