FROM ghcr.io/graalvm/native-image-community:21 AS build
RUN microdnf install -y maven gcc glibc-devel zlib-devel libstdc++-devel gcc-c++

WORKDIR /app
COPY . .

# Run the AOT compilation
RUN ./mvnw -Pnative native:compile -DskipTests

FROM alpine:latest
RUN apk add --no-cache gcompat
WORKDIR /app

# Copy only the binary from the build stage
COPY --from=build /app/target/runestone-bank .

EXPOSE 8080
ENTRYPOINT ["./runestone-bank"]